//! Turning a segment window into a single lossless clip file.

use crate::window::SegmentWindow;
use anyhow::{bail, Context, Result};
use localplay_media::{edit, FfmpegBinaries};
use std::io::Write;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct ClipMetadata {
    pub path: PathBuf,
    pub duration_ms: u64,
    pub size_bytes: u64,
    pub encoder: String,
}

pub struct ClipSplicer;

impl ClipSplicer {
    /// Concatenate whole segments with `-c copy`.
    ///
    /// No leading-segment trim: segment boundaries are keyframes, so `-ss`/`-c copy`
    /// would resolve to the same frame and change nothing (see plan refinements).
    pub fn splice(
        bin: &FfmpegBinaries,
        window: &SegmentWindow,
        out: &Path,
        encoder: &str,
    ) -> Result<ClipMetadata> {
        if window.segments.is_empty() {
            bail!("cannot splice an empty segment window");
        }

        let list = out.with_extension("concat.txt");
        {
            let mut f = std::fs::File::create(&list)
                .with_context(|| format!("creating {}", list.display()))?;
            for seg in &window.segments {
                // Absolute, so the list does not depend on the working directory.
                let p = std::fs::canonicalize(&seg.file)
                    .with_context(|| format!("resolving {}", seg.file.display()))?;
                writeln!(f, "file '{}'", concat_list_path(&p))?;
            }
        }

        edit::concat_lossless(bin, &list, out)?;
        let _ = std::fs::remove_file(&list);

        let info = localplay_media::MediaInfo::probe(bin, out)?;

        // A/V offset **within the produced clip** (spec §11 criterion 8). This is the
        // observable that matters: it compares the audio and video stream timelines of
        // the muxed file. It is NOT the QPC-clock divergence between the two live
        // capture sources, which would require instrumenting the capture path itself.
        let stem = out
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("clip");
        match info.av_drift() {
            Some(d) => tracing::info!(
                "clip {stem}: video {}ms audio {}ms drift {}ms",
                d.video_ms,
                d.audio_ms,
                d.delta_ms
            ),
            None => tracing::warn!(
                "clip {stem}: A/V drift unavailable — ffprobe reported no per-stream \
                 duration (video {}ms, audio {}ms); the streams are present but the \
                 offset cannot be computed honestly",
                opt_ms(info.video.as_ref().and_then(|v| v.duration_ms)),
                opt_ms(info.audio.as_ref().and_then(|a| a.duration_ms)),
            ),
        }

        Ok(ClipMetadata {
            path: out.to_path_buf(),
            duration_ms: info.duration_ms,
            size_bytes: info.size_bytes,
            encoder: encoder.to_string(),
        })
    }
}

/// Render `path` as the path field of one `file '...'` line of an ffmpeg concat list.
///
/// The concat demuxer parses the list itself, so an OS-native path cannot simply be
/// written out as-is (spec §6.2 step 3). Three things have to change:
///
/// * **Verbatim prefixes.** On Windows `std::fs::canonicalize` returns a *verbatim*
///   path — `\\?\C:\Users\...`, or `\\?\UNC\server\share\...` for a network path.
///   ffmpeg has no notion of that prefix and fails to open what follows, so it is
///   stripped first. The UNC form keeps its meaning by becoming `//server/share/...`.
/// * **Backslashes.** The concat list is parsed as an escaped string, and a backslash
///   sitting next to a quote mangles the field — measured on ffmpeg 9.0.2, where a
///   `file '.../it's dir/...'` line was truncated at the quote and a `\'` spelling
///   resolved to neither. Windows spells the separator `\`, so the separator is
///   converted to `/`, which leaves the parser nothing to escape and which ffmpeg
///   accepts on Windows as well.
/// * **Single quotes.** A quote would end the quoted path early. The demuxer's
///   spelling for a literal quote inside a quoted path is the shell's: `'\''`.
///   (Checked against ffmpeg 9.0.2: `file '.../it'\''s.mp4'` opens the file, while
///   both a bare quote and the `\'` spelling fail.)
///
/// The order is load-bearing: the backslashes are converted *before* the quote
/// escaping, so the backslash the escape itself introduces is not rewritten into a
/// slash (which would leave the path ending at the first quote).
///
/// On Unix a backslash is an ordinary filename byte, so the conversion is a
/// Windows-shaped choice; the paths here are scratch-segment paths generated by this
/// application, none of which contain one.
pub fn concat_list_path(path: &Path) -> String {
    let raw = path.to_string_lossy();
    let unverbatim = match raw.strip_prefix(r"\\?\UNC\") {
        // `\\?\UNC\server\share\dir` — a UNC path in verbatim guise.
        Some(rest) => format!("//{rest}"),
        None => raw.strip_prefix(r"\\?\").unwrap_or(&raw).to_string(),
    };
    unverbatim.replace('\\', "/").replace('\'', r"'\''")
}

/// Render an optional millisecond count for the log line, saying "unavailable"
/// rather than pretending a missing value is 0.
fn opt_ms(ms: Option<u64>) -> String {
    ms.map(|m| m.to_string())
        .unwrap_or_else(|| "unavailable".to_string())
}

#[cfg(test)]
mod tests {
    use super::concat_list_path;
    use std::path::Path;

    // These paths are never canonicalised here: on the Unix host this runs on, a
    // Windows path is just a string, which is exactly what makes the prefix and
    // backslash handling — the part that breaks on Windows — testable off Windows.

    #[test]
    fn a_verbatim_windows_path_loses_its_prefix_and_its_backslashes() {
        assert_eq!(
            concat_list_path(Path::new(r"\\?\C:\Users\a\videos\seg-000001.mp4")),
            "C:/Users/a/videos/seg-000001.mp4"
        );
    }

    #[test]
    fn a_verbatim_unc_path_becomes_a_plain_unc_path() {
        assert_eq!(
            concat_list_path(Path::new(r"\\?\UNC\server\share\videos\seg-000001.mp4")),
            "//server/share/videos/seg-000001.mp4"
        );
    }

    #[test]
    fn a_plain_unix_path_is_untouched() {
        assert_eq!(concat_list_path(Path::new("/tmp/a/seg.mp4")), "/tmp/a/seg.mp4");
    }

    #[test]
    fn a_single_quote_is_escaped_so_the_list_stays_valid() {
        assert_eq!(
            concat_list_path(Path::new("/tmp/it's a dir/seg.mp4")),
            r"/tmp/it'\''s a dir/seg.mp4"
        );
    }

    #[test]
    fn quote_escaping_survives_backslash_conversion() {
        // The escape `'\''` contains a backslash: if the conversions ran in the other
        // order it would be rewritten to `/` and the demuxer would read the path as
        // ending at the quote.
        let rendered = concat_list_path(Path::new(r"\\?\C:\a b\it's\seg.mp4"));
        assert_eq!(rendered, r"C:/a b/it'\''s/seg.mp4");
        // The only backslashes left are the ones inside the quote escape; any other
        // one would be read by the demuxer as an escape character.
        assert!(
            !rendered.replace(r"'\''", "").contains('\\'),
            "a path separator survived as a backslash: {rendered}"
        );
    }
}
