//! The token, and the `gamestate_integration_localplay.cfg` the user installs.
//!
//! Spec §7.2: "the `gamestate_integration_localplay.cfg` file is generated by the app and
//! installed by the user; the app does not write into game installation directories on its
//! own". So everything here produces *text* — a token and a file's contents — and the
//! caller decides where to leave it and what to tell the user. Nothing in this module
//! touches a game directory, and there is no code path that could.
//!
//! # How the token reaches the server
//!
//! Valve's `"auth" { "token" "<value>" }` block is echoed back by the game **inside the
//! JSON body** under `"auth"`, as a string field: GSI sends no `Authorization` header and
//! implements no bearer scheme. So the gate in [`crate::gsi`] reads
//! `body.auth["token"]` and compares it in constant time, and the generated file puts the
//! token in the `"auth"` block. (Valve's documentation says the auth fields "will be
//! transmitted as JSON string fields to the endpoint to authenticate the payload"; the
//! block can also carry extra key/value pairs, which is why the parser is a string map.)
//!
//! # The token file
//!
//! A token has to be the same across runs, or the user would have to re-install the
//! `.cfg` every time the application starts. So the first run generates one and keeps it
//! in the application data directory ([`load_or_create_token`]); later runs read it. It is
//! created `0600` where the platform has modes. On Windows it lives in
//! `%LOCALAPPDATA%\\localplay`, which is per-user, and no ACL hardening is applied — the
//! token only gates a listener that is unreachable from anything but this machine.

use anyhow::{bail, Context, Result};
use std::path::Path;

/// How many random bytes a token holds. 256 bits, hex-encoded to 64 characters: Valve's
/// own example is a short string, but there is no reason to make a local process's guess
/// cheap, and the value is copied once, by a human, out of a file the application wrote.
pub const TOKEN_BYTES: usize = 32;

/// The path the GSI listener answers on. One path, so a request to anything else is a 404
/// rather than an accidental payload.
pub const DEFAULT_PATH: &str = "/gsi";

/// Generate a token from the operating system's randomness.
pub fn generate_token() -> Result<String> {
    let mut bytes = [0u8; TOKEN_BYTES];
    getrandom::fill(&mut bytes).context("reading randomness for the GSI token")?;
    Ok(hex(&bytes))
}

/// Read the token from `path`, generating and storing one if there is not one there yet.
///
/// An existing file that does not hold a plausible token is an error rather than silently
/// replaced: overwriting it would leave the user's already-installed `.cfg` holding a token
/// the listener no longer accepts, which looks exactly like a broken integration.
pub fn load_or_create_token(path: &Path) -> Result<String> {
    match std::fs::read_to_string(path) {
        Ok(text) => {
            let token = text.trim().to_string();
            validate_token(&token).with_context(|| {
                format!(
                    "{} does not hold a usable GSI token; delete it to have a new one \
                     generated (the game's cfg file must then be replaced too)",
                    path.display()
                )
            })?;
            Ok(token)
        }
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            let token = generate_token()?;
            if let Some(dir) = path.parent() {
                std::fs::create_dir_all(dir)
                    .with_context(|| format!("creating {}", dir.display()))?;
            }
            std::fs::write(path, format!("{token}\n"))
                .with_context(|| format!("writing {}", path.display()))?;
            restrict_to_owner(path);
            Ok(token)
        }
        Err(err) => Err(err).with_context(|| format!("reading {}", path.display())),
    }
}

/// A token must be hex and long enough to be worth having: anything else is a mistake
/// (a truncated file, an editor's newline handling, a user typing something) and is better
/// reported than accepted.
fn validate_token(token: &str) -> Result<()> {
    if token.len() != TOKEN_BYTES * 2 {
        bail!("a token is {} hex characters", TOKEN_BYTES * 2);
    }
    if !token.bytes().all(|b| b.is_ascii_hexdigit()) {
        bail!("a token is hex");
    }
    Ok(())
}

/// Owner-only where the platform has file modes. Best effort by design: the failure is not
/// worth refusing to start over, so it is logged by the caller's tracing if at all.
#[cfg(unix)]
fn restrict_to_owner(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
}

/// Windows keeps the file in the per-user application data directory; see the module docs.
#[cfg(not(unix))]
fn restrict_to_owner(_path: &Path) {}

/// The Counter-Strike 2 / CS:GO integration file, ready to install (spec §7.2).
///
/// Pure text in, text out: what it contains is asserted literally by the tests below,
/// because it is a file a human copies into a game directory and cannot be checked at run
/// time from here.
pub fn integration_cfg(port: u16, token: &str) -> String {
    let data = [
        ("provider", "1"),
        ("map", "1"),
        ("round", "1"),
        ("bomb", "1"),
        ("player_state", "1"),
        ("player_match_stats", "1"),
    ];
    cfg_text(
        "Counter-Strike 2 / CS:GO",
        "...\\Counter-Strike Global Offensive\\game\\csgo\\cfg\\gamestate_integration_localplay.cfg",
        port,
        token,
        &data,
    )
}

/// The Dota 2 integration file. Its data blocks are Dota's, not Counter-Strike's.
pub fn integration_cfg_dota(port: u16, token: &str) -> String {
    let data = [
        ("provider", "1"),
        ("map", "1"),
        ("player", "1"),
        ("hero", "1"),
    ];
    cfg_text(
        "Dota 2",
        "...\\dota 2 beta\\game\\dota\\cfg\\gamestate_integration\\gamestate_integration_localplay.cfg",
        port,
        token,
        &data,
    )
}

/// The file both of the above are built from. The `//` comments are legal in Valve's
/// KeyValues format (Valve's own example `gamestate_integration_consolesample.cfg` uses
/// them) and they are how the file explains itself to the user, who has to install it by
/// hand.
fn cfg_text(game: &str, install_path: &str, port: u16, token: &str, data: &[(&str, &str)]) -> String {
    let mut out = String::new();
    out.push_str(&format!("// localplay — {game} Game State Integration (generated)\n"));
    out.push_str("// Install this file as:\n");
    out.push_str(&format!("//   {install_path}\n"));
    out.push_str("// localplay listens on loopback only; nothing here leaves this machine.\n");
    out.push('\n');
    out.push_str("\"localplay\"\n{\n");
    out.push_str(&format!("    \"uri\"       \"http://127.0.0.1:{port}{DEFAULT_PATH}\"\n"));
    // timeout/buffer/throttle are Valve's recommended local values; heartbeat is what keeps
    // a payload arriving during a quiet stretch of a match, so a heartbeat-based derivation
    // (the bomb timer, in particular) is not waiting on a state change that never comes.
    out.push_str("    \"timeout\"   \"1.0\"\n");
    out.push_str("    \"buffer\"    \"0.1\"\n");
    out.push_str("    \"throttle\"  \"0.1\"\n");
    out.push_str("    \"heartbeat\" \"10.0\"\n");
    out.push('\n');
    out.push_str("    // Echoed back in the payload's \"auth\" block; localplay rejects any\n");
    out.push_str("    // request whose token does not match the one it generated.\n");
    out.push_str("    \"auth\"\n    {\n");
    out.push_str(&format!("        \"token\"     \"{token}\"\n"));
    out.push_str("    }\n");
    out.push('\n');
    out.push_str("    \"data\"\n    {\n");
    for (name, value) in data {
        // Both halves are quoted: `"map" "1"`. A missing quote makes the file invalid for
        // the game, and nothing here can run the game to find out — which is why the test
        // below checks the rendered lines rather than the presence of the keys.
        out.push_str(&format!("        \"{name}\"{}\n", pad(name, value)));
    }
    out.push_str("    }\n}\n");
    out
}

/// One `"key" "value"` line, aligned so the values line up — which is how Valve's own
/// example file is written.
///
/// Never fewer than one space between the two tokens: `"player_match_stats""1"` is a pair
/// with nothing separating it, which is at best fragile for a KeyValues parser and at worst
/// a value the game reads as part of the key. The longest name here is 18 characters, so
/// this only bites the one line — which is exactly the line a test has to catch, because
/// nothing on this machine can run the game to complain.
fn pad(name: &str, value: &str) -> String {
    const WIDTH: usize = 20;
    let spaces = WIDTH.saturating_sub(name.len() + 2).max(1);
    format!("{}\"{value}\"", " ".repeat(spaces))
}

fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(DIGITS[(byte >> 4) as usize] as char);
        out.push(DIGITS[(byte & 0x0f) as usize] as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_generated_token_is_256_bits_of_hex() {
        let token = generate_token().expect("the OS provides randomness");
        assert_eq!(token.len(), TOKEN_BYTES * 2);
        assert!(token.bytes().all(|b| b.is_ascii_hexdigit()), "got {token}");
        assert_eq!(token, token.to_lowercase(), "lower-case hex, so two spellings of one value cannot both exist");
    }

    #[test]
    fn two_generated_tokens_differ() {
        let a = generate_token().unwrap();
        let b = generate_token().unwrap();
        assert_ne!(a, b, "a token that repeats is not random");
    }

    #[test]
    fn the_counter_strike_cfg_is_the_file_a_user_can_install() {
        let token = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let text = integration_cfg(45671, token);

        // The endpoint, which is the one thing that has to be right.
        assert!(
            text.contains("\"uri\"       \"http://127.0.0.1:45671/gsi\""),
            "the uri must name loopback and the configured port:\n{text}"
        );
        // The token, exactly once: a file with it twice would be a file that leaks it.
        assert_eq!(text.matches(token).count(), 1, "the token appears once:\n{text}");
        assert!(text.contains("\"auth\"\n    {\n"), "in the auth block:\n{text}");
        // The key structure Valve parses.
        assert!(text.starts_with("//"), "it explains itself to the user:\n{text}");
        assert!(text.contains("\"localplay\"\n{"), "the block is named:\n{text}");
        assert!(text.trim_end().ends_with('}'), "and closed:\n{text}");
        assert_eq!(
            text.matches('{').count(),
            text.matches('}').count(),
            "every block is closed:\n{text}"
        );
        assert_eq!(text.matches('"').count() % 2, 0, "quotes are balanced:\n{text}");
        // Only loopback appears, and no other host is named anywhere in the file.
        assert!(text.contains("127.0.0.1"), "loopback only:\n{text}");
        assert!(!text.contains("0.0.0.0"), "never every interface:\n{text}");
        assert!(
            text.contains("\"player_match_stats\""),
            "the blocks the derivation reads are subscribed:\n{text}"
        );

        // Every subscribed block is a *quoted pair*. This is the assertion that matters to
        // a user: a `gamestate_integration` file with a half-quoted value is a file the game
        // silently ignores, and there is no CS2 here to notice that for us.
        for (name, value) in [
            ("provider", "1"),
            ("map", "1"),
            ("round", "1"),
            ("bomb", "1"),
            ("player_state", "1"),
            ("player_match_stats", "1"),
        ] {
            let pad = " ".repeat((20 - (name.len() + 2)).max(1));
            let expected = format!("        \"{name}\"{pad}\"{value}\"");
            assert!(text.contains(&expected), "expected the line {expected:?} in:\n{text}");
        }
    }

    #[test]
    fn every_line_of_the_cfg_is_a_block_name_or_a_quoted_pair() {
        // KeyValues is `"key" "value"`. A line with an odd number of quotes, or a value
        // outside quotes, is a file the game will not read — and the only machine that
        // could tell us otherwise is running CS2, which is not this one.
        let text = integration_cfg(45671, "0123456789abcdef0123456789abcdef");
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with("//") || line == "{" || line == "}" {
                continue;
            }
            assert_eq!(
                line.matches('"').count() % 2,
                0,
                "a line with an unbalanced quote: {line:?}"
            );
            assert!(
                matches!(line.matches('"').count(), 2 | 4),
                "a KeyValues line is a block name or a key/value pair: {line:?}"
            );
            if line.matches('"').count() == 4 {
                assert!(
                    line.ends_with('"'),
                    "a key/value pair ends with its value's closing quote: {line:?}"
                );
                // `"key"` then at least one space then `"value"`.
                let after_key = &line[line.find('"').expect("an opening quote") + 1..];
                let after_key = &after_key[after_key.find('"').expect("a closing quote") + 1..];
                let separator = after_key.len() - after_key.trim_start().len();
                assert!(
                    separator >= 1,
                    "the key and its value must be separated by whitespace: {line:?}"
                );
                assert!(
                    after_key.trim_start().starts_with('"'),
                    "and the value must be quoted: {line:?}"
                );
            }
        }
        // The same for the Dota file, whose block list differs.
        let dota = integration_cfg_dota(45671, "0123456789abcdef0123456789abcdef");
        for line in dota.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with("//") || line == "{" || line == "}" {
                continue;
            }
            assert!(matches!(line.matches('"').count(), 2 | 4), "{line:?}");
        }
    }

    #[test]
    fn the_dota_cfg_subscribes_dotas_blocks() {
        let token = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
        let text = integration_cfg_dota(45671, token);
        assert!(text.contains("\"uri\"       \"http://127.0.0.1:45671/gsi\""), "got:\n{text}");
        assert_eq!(text.matches(token).count(), 1);
        for block in ["\"provider\"", "\"map\"", "\"player\"", "\"hero\""] {
            assert!(text.contains(block), "Dota needs {block}:\n{text}");
        }
        assert!(
            !text.contains("player_match_stats"),
            "a Counter-Strike block would be noise in a Dota file:\n{text}"
        );
    }

    #[test]
    fn the_port_and_the_path_in_the_file_are_the_ones_the_listener_uses() {
        // The two halves of the integration are generated by different modules; this is the
        // assertion that they agree on the endpoint.
        for port in [1024u16, 45671, 65535] {
            let text = integration_cfg(port, "00");
            assert!(
                text.contains(&format!("http://127.0.0.1:{port}{DEFAULT_PATH}")),
                "got:\n{text}"
            );
        }
    }

    #[test]
    fn a_token_file_is_created_once_and_reused_afterwards() {
        let dir = tempfile::tempdir().expect("a temp dir");
        let path = dir.path().join("gsi-token.txt");

        let first = load_or_create_token(&path).expect("the first run generates one");
        assert_eq!(first.len(), TOKEN_BYTES * 2);
        let second = load_or_create_token(&path).expect("the second run reads the same one");
        assert_eq!(first, second, "a token that changed would break the installed cfg");
        assert!(path.is_file(), "and it is kept for the next run");
    }

    #[cfg(unix)]
    #[test]
    fn a_token_file_is_readable_only_by_its_owner() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("gsi-token.txt");
        load_or_create_token(&path).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600, "mode was {mode:o}");
    }

    #[test]
    fn a_token_file_that_does_not_hold_a_token_is_refused_rather_than_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("gsi-token.txt");

        for content in ["", "hunter2", "0123456789abcdef", &"a".repeat(65), &"z".repeat(64)] {
            std::fs::write(&path, content).unwrap();
            let err = load_or_create_token(&path).expect_err("not a token");
            assert!(
                format!("{err:#}").contains("delete it"),
                "the error must say what to do: {err:#}"
            );
            assert_eq!(std::fs::read_to_string(&path).unwrap(), content, "and change nothing");
        }
    }

    #[test]
    fn a_token_file_with_trailing_whitespace_still_holds_its_token() {
        // Editors add a newline; that must not invalidate a working installation.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("gsi-token.txt");
        let token = "ab".repeat(TOKEN_BYTES);
        std::fs::write(&path, format!("  {token}  \n\n")).unwrap();
        assert_eq!(load_or_create_token(&path).unwrap(), token);
    }
}
